const DISCORD_ROUTER = "https://discord.gg/MsXks2HU9h";
const FACEBOOK_ROUTER = "https://www.facebook.com/spinellabs";
const FOOTER_AUDIT_ROUTER = "FOOTER_AUDIT_ROUTER";
const FOOTER_DOCS_ROUTER = "FOOTER_DOCS_ROUTER";
const FOOTER_NFT_ROUTER = "FOOTER_NFT_ROUTER";
const FOOTER_PRIVACY_ROUTER = "FOOTER_PRIVACY_ROUTER";
const FOOTER_SNAPTASK_ROUTER = "FOOTER_SNAPTASK_ROUTER";
const FOOTER_SPINEL_BLOCKCHAIN_ROUTER = "FOOTER_SPINEL_BLOCKCHAIN_ROUTER";
const FOOTER_SPINEL_EXCHANGE_ROUTER = "FOOTER_SPINEL_EXCHANGE_ROUTER";
const FOOTER_SPINEL_LAUNCHPAD_ROUTER = "FOOTER_SPINEL_LAUNCHPAD_ROUTER";
const FOOTER_SPINEL_WALLET_ROUTER = "FOOTER_SPINEL_WALLET_ROUTER";
const FOOTER_TERMS_ROUTER = "FOOTER_TERMS_ROUTER";
const HOME_ROUTER = "";
const MAIL_ROUTER = "mailto:contact@spinel.launchpad";
const TELEGRAM_ROUTER = "https://t.me/Spinel_Labs_Global";
const TWITTER_ROUTER = "https://x.com/spinellabs";
const YOUTUBE_ROUTER = "https://www.youtube.com/@SpinelLab";
const HOME = "/";
const LAUNCHPAD = "/launchpad";
const HISTORY = "/history";
export const Routers = {
  HOME,
  LAUNCHPAD,
  HISTORY,
  DISCORD_ROUTER,
  FACEBOOK_ROUTER,
  FOOTER_AUDIT_ROUTER,
  FOOTER_DOCS_ROUTER,
  FOOTER_NFT_ROUTER,
  FOOTER_PRIVACY_ROUTER,
  FOOTER_SNAPTASK_ROUTER,
  FOOTER_SPINEL_BLOCKCHAIN_ROUTER,
  FOOTER_SPINEL_EXCHANGE_ROUTER,
  FOOTER_SPINEL_LAUNCHPAD_ROUTER,
  FOOTER_SPINEL_WALLET_ROUTER,
  FOOTER_TERMS_ROUTER,
  HOME_ROUTER,
  MAIL_ROUTER,
  TELEGRAM_ROUTER,
  TWITTER_ROUTER,
  YOUTUBE_ROUTER,
};
