const COLOR_BG = "#090612"
const COLOR_BLACK = "#000"
const COLOR_BORDER = "#A6A6EF"
const COLOR_BUTTON_SECONDARY = "#8F8FFF"
const COLOR_CAPTION_14 = "#6F819F"
const COLOR_FOOTER = "#94A7C6"
const COLOR_LINK = "#94A7C6CC"
const COLOR_TEXT = "#FFFFFFB2"
const COLOR_TEXT_MEDIUM = "#7E8FF0"
const COLOR_TITLE = "#CCCCF9"
const COLOR_WHITE = "#FFF"

export const Colors = {
  COLOR_BG,
  COLOR_BLACK,
  COLOR_BORDER,
  COLOR_BUTTON_SECONDARY,
  COLOR_CAPTION_14,
  COLOR_FOOTER,
  COLOR_LINK,
  COLOR_TEXT,
  COLOR_TEXT_MEDIUM,
  COLOR_TITLE,
  COLOR_WHITE,
}
